//the data
String[] names = {"Paintings", 
                  "Drawings", 
                  "Sculpture", 
                  "Prints", 
                  "Photographs",
                  "Accessories (non-art)",
                  "Albums",
                  "Amulets",
                  "Architectural Elements",
                  "Archival Material",
                  "Armor",
                  "Artists' Materials",
                  "Artists' Tools",
                  "Audiovisual Works",
                  "Books",
                  "Boxes",
                  "Brick Stamps",
                  "Calligraphy",
                  "Cameos",
                  "Coins",
                  "Fragments",
                  "Furnishings",
                  "Furniture",
                  "Gems",
                  "Graphic Design",
                  "Inscriptions",
                  "Jewelry",
                  "Lighting Devices",
                  "Manuscripts",
                  "Material Specimens",
                  "Measuring Devices",
                  "Medals and Medallions",
                  "Mirrors",
                  "Mosaics",
                  "Multiples",
                  "Musical Instruments",
                  "Paintings with Calligraphy",
                  "Paintings with Text",
                  "Performance Artifacts",
                  "Plaques",
                  "Portfolios",
                  "Recreational Artifacts",
                  "Riding Equipment",
                  "Ritual Implements",
                  "Rubbings",
                  "Seals",
                  "Stained Glass",
                  "Tablets",
                  "Text",
                  "Textile Arts",
                  "Timepieces",
                  "Tokens",
                  "Tools and Equipment",
                  "Unidentified",
                  "Vessels",
                  "Weapons and Ammunition"};

int[][] planets = {{8,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,3,1,1,5,2,10,1,2,1,1,10,3,1,21,11,25,2},
                   {1,1,1,1,1,1,3,1,4,1,6,2,20,9,56,1},
                   {1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,2,1,1,1,1,2,1,1,2,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,2,1,1,2,1,1,2,1,1,1,6,2,13,4,18,1},
                   {3,1,1,1,1,1,1,1,1,2,1,10,2,14,1,1,14,4,30,2,22,1,1},
                   {1,6,12,83,1,1},
                    {94,6},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1},
                    {1}};
                   
String[][] labels = {{"(not assigned)", "2nd millennium BC", "1st century BC", "1st century BC-1st century AD", "1st century AD", "2nd century AD", "2nd-3rd centuries", "3rd century", "7th century", "7th-10th centuries", "8th century", "8th-9th centuries", "9th century", "9th-10th centuries", "10th century", "10th-13th centuries", "11th century", "11th-13th centuries", "12th century", "12th-13th centuries", "12th-14th centuries", "13th century", "13th-14th centuries", "13th-15th centuries", "14th century", "14th-15th centuries", "14th-16th centuries", "14th-17th centuries", "15th century", "15th-12th centuries BC", "15th-16th centuries", "16th century", "16th-17th centuries", "17th century", "17th-16th centuries BC", "17th-18th centuries", "17th-19th centuries", "18th and 19th centuries", "18th century", "18th-19th centuries", "18th-20th centuries", "19th century", "19th-20th centuries", "20th century", "21st century"},
                     {"(not assigned)", "13th century", "14th century", "14th-15th centuries", "15th century", "15th-16th centuries", "16th century", "16th-17th centuries", "17th century", "17th-18th centuries", "18th century", "18th-19th centuries", "19th century", "19th-20th centuries", "20th century", "21st century"},
                     {"(not assigned)", "Unidentified century", "17th-14th centuries BC", "17th-16th centuries BC", "16th-11th centuries BC", "16th-13th centuries BC", "16th-14th centuries BC", "15th century BC", "14th century BC", "14th-11th centuries BC", "14th-12th centuries BC", "14th-13th centuries BC", "13th-12th centuries BC", "13th century BC", "12th-10th centuries BC", "11th-7th centuries BC", "11th-9th centuries BC", "10th-7th centuries BC", "10th-8th centuries BC", "10th-9th centuries BC", "10th century BC", "9th-6th centuries BC", "9th-7th centuries BC", "9th-8th centuries BC", "9th century BC", "8th-1st centuries BC", "8th-2nd centuries BC", "8th-4th centuries BC", "8th-5th centuries BC", "8th-6th centuries BC", "8th-7th centuries BC", "8th century BC", "7th-1st centuries BC", "7th-4th centuries BC", "7th-5th centuries BC", "7th-6th centuries BC", "7th century BC", "6th-1st centuries BC", "6th-2nd centuries BC", "6th-3rd centuries BC", "6th-4th centuries BC", "6th-5th centuries BC", "6th century BC", "5th century BC", "5th-1st centuries BC", "5th-2nd centuries BC", "5th-3rd centuries BC", "5th-4th centuries BC", "4th-1st centuries BC", "4th-1st millennia BC", "4th-2nd centuries BC", "4th-3rd centuries BC", "4th-3rd millennia BC", "4th century BC", "4th century BC-4th century AD", "4th millennium BC", "3rd millennium BC", "3rd-1st centuries BC", "3rd-2nd centuries BC", "3rd-2nd millennia BC", "3rd century BC", "3rd century BC-1st century AD", "3rd century BC-3rd century AD", "2nd millennium BC", "2nd-1st centuries BC", "2nd-1st millennia BC", "2nd century BC-1st  century AD", "2nd century BC", "1st century BC", "1st millennium BC", "1st millennium BC-1st millenium AD", "1st century AD", "1st century BC-1st century AD", "1st century BC-2nd century AD", "1st century BC-3rd century AD", "1st millennium AD", "1st-2nd centuries", "1st-3rd centuries", "1st-4th centuries", "1st-5th centuries", "2nd century", "2nd century AD", "2nd-3rd centuries", "2nd-3rd centuries AD", "2nd-4th centuries", "2nd-6th centuries", "3rd century", "3rd century AD", "3rd-4th centuries", "3rd-5th centuries", "3rd-7th centuries", "4th century", "4th-10th centuries", "4th-5th centuries", "4th-6th centuries", "4th-7th centuries", "5th century", "5th-6th centuries", "5th-7th centuries", "6th century", "6th-10th centuries", "6th-7th centuries", "6th-8th centuries", "6th-9th centuries", "7th century", "7th-10th centuries", "7th-8th centuries", "8th century", "8th-10th centuries", "8th-15th centuries", "8th-9th centuries", "9th century", "9th-10th centuries", "9th-11th centuries", "9th-12th centuries", "10th century", "10th-11th centuries", "10th-12th centuries", "10th-17th centuries", "11th century", "11th-12th centuries", "11th-13th centuries", "11th-15th centuries", "12th century", "12th-13th centuries", "12th-14th centuries", "13th century", "13th-14th centuries", "13th-15th centuries", "14th century", "14th-15th centuries", "14th-16th centuries", "14th-17th centuries", "15th century", "15th-16th centuries", "15th-17th centuries", "16th century", "16th-17th centuries", "16th-19th centuries", "17th century", "17th-18th centuries", "17th-19th centuries", "17th-20th centuries", "18th century", "18th-19th centuries", "19th century", "19th-20th centuries", "20th century", "21st century"},
                     {"(not assigned)", "10th century", "10th-12th centuries", "11th century", "12th century", "12th-14th centuries", "13th century", "14th century", "14th-16th centuries", "15th century", "15th-16th centuries", "16th century", "16th-17th centuries", "17th century", "17th-18th centuries", "17th-19th centuries", "18th century", "18th-19th centuries", "19th century", "19th-20th centuries", "20th century", "20th-21st centuries", "21st century"},
                     {"(not assigned)", "19th century", "19th-20th centuries", "20th century", "20th-21st centuries", "21st century"},
                     {"(not assigned)", "19th century"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"},
                    {"(not assigned)"}};

int[] diameters = {30,120,30,300,340,10,10,10,10,40,10,10,10,10,10,10,10,10,10,90,20,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,30,10};

